document.write("<table width=\"850\" border=\"0\" height=\"184\">");
document.write("<tbody>");
document.write("<tr>");
document.write("<td width=\"350\"> <img src=\"Images/athens-lbz.JPG\" alt=\"Ben-Zheng Li\" width=\"320\" height=\"250\"> <\/td>");
document.write("<td>");
document.write("<h1>Ben-Zheng Li (李本正)<\/h1>");
document.write("<br>");
document.write("<b>Assistant Professor<\/b>");
document.write("<br>");
// 注意这里的引号转义和标签匹配
document.write("<a href=\"https://maths.ccnu.edu.cn/\"> School of Mathematics and Statistics <\/a>");
document.write("<br>");
document.write("<a href=\"https://www.ccnu.edu.cn/\"> Central China Normal University <\/a>");
document.write("<br>");
document.write("<b>Contact info:<\/b><br>");
document.write(" Wuhan, Hubei, China. <br>");
document.write("Office: Room 306, Math. Building<br>");
document.write("E-mail: mathlibz@ccnu.edu.cn, lbz1604179601@126.com<br>");
document.write("&nbsp;");
document.write("<a href=\"https://scholar.google.com/citations?user=pXU2ncUAAAAJ&hl=en\"><img src=\"Images/scholar.png\" alt=\"Scholar\" width=\"25\" height=\"25\" border=\"0\"> <\/a> &nbsp;");
document.write("<a href=\"https://www.researchgate.net/profile/Ben-Zheng-Li-2?ev=hdr_xprf\"><img src=\"Images/Researchgate.jpg\" alt=\"Researchgate\" width=\"25\" height=\"25\" border=\"0\"> <\/a> &nbsp;");
document.write("<a href=\"https://github.com/benzhengli\"><img src=\"Images/GitHub-Mark-120px-plus.png\" alt=\"GitHub\" width=\"25\" height=\"25\" border=\"0\"> <\/a>");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/tbody>");
document.write("<\/table>");
document.write("<br>");
document.write("<br>");
